import { precacheAndRoute } from 'workbox-precaching';

// manifest import will be autogenerated by webpack
precacheAndRoute(self.__WB_MANIFEST || []);

self.addEventListener("message", (evt) => {
    const client = evt.source;
    client.postMessage(`Pong: ${ evt.data }`);
});

self.addEventListener("activate", (evt) => {
    console.log("Active APP WORKER");
});